name: Container Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Create a simple Dockerfile inline to ensure it works
      - name: Create test Dockerfile
        run: |
          cat > Dockerfile << 'EOF'
          FROM ubuntu:20.04
          RUN apt-get update && apt-get install -y curl
          CMD ["bash"]
          EOF

      - name: Build Docker image
        run: |
          docker build -t test-image:latest .
          echo "Docker build successful"

      - name: Run Trivy vulnerability scanner
        run: |
          # Install Trivy directly
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.35.0
          
          # Run the scan and save results
          trivy image --format json --output trivy-results.json test-image:latest
      
      - name: Show scan results summary
        run: |
          echo "Scan completed. Results saved to trivy-results.json"
          ls -la
          
      - name: Create GitHub Pages directory
        run: |
          mkdir -p public
          cp trivy-results.json public/
          echo "<html><body><h1>Trivy Scan Results</h1><p><a href='trivy-results.json'>Download JSON Report</a></p></body></html>" > public/index.html
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
